=== veN1337/wba2-phase1/src/Aufgabe3d.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xsd:element name="title" type="xsd:string"></xsd:element>
    <xsd:element name="workingtime" type="xsd:string"></xsd:element>
    <xsd:element name="difficulty" type="xsd:string"></xsd:element>
    <xsd:element name="kcal" type="xsd:int"></xsd:element>

    <xsd:attribute name="recipe_id" type="xsd:ID"></xsd:attribute>
    <xsd:attribute name="step_id" type="xsd:ID"></xsd:attribute>
    <xsd:attribute name="comment_id" type="xsd:ID"></xsd:attribute>
    <xsd:attribute name="amount" type="xsd:int"></xsd:attribute>
    <xsd:attribute name="unit" type="xsd:string"></xsd:attribute>

    <xsd:element name="recipes">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element ref="recipe" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="recipe">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element ref="title"></xsd:element>
    			<xsd:element ref="difficulty"></xsd:element>
    			<xsd:element ref="workingtime"></xsd:element>
    			<xsd:element ref="kcal"></xsd:element>
    			<xsd:element ref="ingredients"></xsd:element>
    			<xsd:element ref="preperation"></xsd:element>
    			<xsd:element ref="comments"></xsd:element>
    		</xsd:sequence>
    		<xsd:attribute ref="recipe_id" use="required"></xsd:attribute>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="ingredients">
    	<xsd:complexType>
    		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
    			<xsd:element ref="ingredient" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="ingredient">
    	<xsd:complexType>
    		<xsd:simpleContent>
    			<xsd:extension base="xsd:string">
    				<xsd:attribute ref="amount" use="required"></xsd:attribute>
    				<xsd:attribute ref="unit" use="required"></xsd:attribute>
    			</xsd:extension>
    		</xsd:simpleContent>    		
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="step">
    	<xsd:complexType>
    		<xsd:simpleContent>
    			<xsd:extension base="xsd:string">
    				<xsd:attribute ref="step_id" use="required"></xsd:attribute>
    			</xsd:extension>
    		</xsd:simpleContent>
    	</xsd:complexType>
    </xsd:element>

    <xsd:element name="preperation">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element ref="step" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>
    

    <xsd:element name="comments">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element ref="comment" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>
    
    <xsd:element name="comment">
    	<xsd:complexType>
    		<xsd:simpleContent>
    			<xsd:extension base="xsd:string">
    				<xsd:attribute ref="comment_id" use="required"></xsd:attribute>
    			</xsd:extension>
    		</xsd:simpleContent>
    	</xsd:complexType>
    </xsd:element>
</xsd:schema>

=== veN1337/wba2-phase1/src/Aufgabe3d.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3d.xsd">
    <recipe recipe_id="1">
        <title>Nußecken</title>
        <difficulty>normal</difficulty>
        <workingtime>ca. 45 Minuten</workingtime>
        <kcal>0</kcal>
        <ingredients>
            <ingredient amount="130" unit="Gramm">Butter oder Margarine</ingredient>
            <ingredient amount="130" unit="Gramm">Zucker</ingredient>
            <ingredient amount="2" unit="">Eier</ingredient>
            <ingredient amount="300" unit="Gramm">Mehl</ingredient>
            <ingredient amount="1" unit="Teelöffel">Backpulver</ingredient>
        </ingredients>
        <preperation>
            <step step_id="1">Knetteig bereiten und auf einem gefetteten Backblech ausrollen.</step>
            <step step_id="2">Aprikosenkonfitüre auf den ausgerollten Teig streichen.</step>
            <step step_id="3">Butter, Zucker und Vanillinzucker erhitzen, bis der Zucker sich gelöst hat.</step>
            <step step_id="4">Nüsse zusammen mit Wasser unter die Butter-Zucker-Masse rühren.</step>
            <step step_id="5">Auf den Teig geben.</step>
        </preperation>
        <comments>
            <comment comment_id="1">Super. Schmeckt gut!</comment>
            <comment comment_id="2">Naja...</comment>
        </comments>
    </recipe>
    <recipe recipe_id="2">
        <title>Butter mit Zucker</title>
        <difficulty>normal</difficulty>
        <workingtime>ca. 45 Minuten</workingtime>
        <kcal>0</kcal>
        <ingredients>
            <ingredient amount="130" unit="Gramm">Butter oder Margarine</ingredient>
            <ingredient amount="130" unit="Gramm">Zucker</ingredient>
        </ingredients>
        <preperation>
            <step step_id="1">Alles zusammen mischen.</step>
        </preperation>
    </recipe>
</recipes>
